= Reactive Systems in Java

== Build Resilient, Event-Driven Architecture with https://quarkus.io/[Quarkus] and https://camel.apache.org/[Apache Camel]

== Links

- https://github.com/cescoffier/reactive-systems-in-java[Official Git Book Page]
- https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.13/index.html[SmallRye Reactive Messaging]
- https://camel.apache.org/components/3.14.x/kafka-component.html[Kafka Component]
- https://github.com/minyk/docker-artemis/blob/master/docker-compose.yml[Docker Apache Artemis]

== PS Command RSS

[source,bash]
----
ps -e | grep thorntail
ps -o pid,rss,command -p {{id}} | awk '{$2=int($2/1024)"M";}{print;}'
java -Xmx48m -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -jar {{jar}}
./mvnw clean package -Dquarkus.kubernetes.deploy=true
----

== Use wrk tool to stress the app endpoint

[source,bash]
----
wrk -t 10 -c50 -d40s http://localhost:8080/hello
----

* Container density is a key characteristic of cloud deployments with Kubernetes

* The Reactive Manifesto

** _Responsive_ Able to handle requests in a timely fashion
** _Resilient_ Able to manage failure gracefully
** _Elastic_ Able to scale up and down according to the load and resources
** _Message Driven_ Using asynchronous message-based communication among the components forming the system, async messages ensures loose coupling, isolation and location transparency

[source,java]
----
class FooMulti {
  public Multi<Product> getRecommendations() {
    return Multi.createFrom().ticks().every(Duration.ofSeconds(1))
      .onOverflow().drop()
      .onItem().transformToUniAndConcatenate(x-> product.getRecommendedProduct());
  }
};
----

== Redis Cluster

[source,bash]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 --name redis_quarkus_test -p 6379:6379 redis:5.0.6
----

== Debezium Connector

[source,bash]
----
curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" http://localhost:8083/connectors/ -d @register.json
curl -H "Accept:application/json" localhost:8083/connectors/
curl -X GET -H "Accept:application/json" localhost:8083/connectors/customer-connector
----

== Check Kafka Topics

[source,bash]
----
docker exec -ti kafka bin/kafka-topics.sh --list --zookeeper zookeeper:2181
----

== Topics created

[source,html]
----
__consumer_offsets
my_connect_configs
my_connect_offsets
my_connect_statuses
quarkus-db-server.public.customer
quarkus-db-server.public.orders
----

== Camel Consumer Log from Update Operation PUT ##"name":"Marsha Willis 123"}##

[source,bash]
----
2022-01-29 11:31:34,557 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer]) Message received from Kafka : {"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":false,"field":"id"},{"type":"string","optional":false,"field":"name"}],"optional":true,"name":"quarkus_db_server.public.customer.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":false,"field":"id"},{"type":"string","optional":false,"field":"name"}],"optional":true,"name":"quarkus_db_server.public.customer.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"field":"transaction"}],"optional":false,"name":"quarkus_db_server.public.customer.Envelope"},"payload":{"before":null,"after":{"id":2,"name":"Marsha Willis 123"},"source":{"version":"1.5.4.Final","connector":"postgresql","name":"quarkus-db-server","ts_ms":1643466693971,"snapshot":"false","db":"quarkus_test","sequence":"[\"24203552\",\"24203552\"]","schema":"public","table":"customer","txId":542,"lsn":24203608,"xmin":null},"op":"u","ts_ms":1643466694089,"transaction":null}}

2022-01-29 11:31:34,558 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer])     on the topic quarkus-db-server.public.customer
2022-01-29 11:31:34,558 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer])     on the partition 0
2022-01-29 11:31:34,558 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer])     with the offset 17
2022-01-29 11:31:34,559 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer])     with the key {"schema":{"type":"struct","fields":[{"type":"int64","optional":false,"field":"id"}],"optional":false,"name":"quarkus_db_server.public.customer.Key"},"payload":{"id":2}}

----

== SmallRye Reactive Messaging

=== Concepts

- Messages, Payloads and Metadata

. Message is an envelope around a payload, the application is going to receive, process and send Messages, Each Message<T> contains a payload of type <T>.
. Channels and Streams Inside your application, Messages transit on channel.
. A channel is a virtual destination identified by a name.
. Each connector is dedicated to a specific technology, for example, a Kafka Connector only deals with Kafka.
. You don’t necessarily need a connector, when your application does not use connectors, everything happens in-memory

. Connectors A connector is a piece of code that connects to a broker and
.. subscribe/poll/receive messages from the broker and propagate them to the application
.. send/write/dispatch messages provided by the application to the broker

....
String payload = message.getPayload();
Optional<MyMetadata> metadata = message.getMetadata(MyMetadata.class);
....

[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>smallrye-reactive-messaging-provider</artifactId>
  <version>3.13.0</version>
</dependency>
<dependency>
 <groupId>io.smallrye.reactive</groupId>
 <artifactId>mutiny-reactive-streams-operators</artifactId>
 <version>1.1.2</version>
</dependency>
<dependency>
  <groupId>org.jboss.weld.se</groupId>
  <artifactId>weld-se-core</artifactId>
  <version>3.1.8.Final</version>
</dependency>
<dependency>
  <groupId>io.smallrye.config</groupId>
  <artifactId>smallrye-config</artifactId>
  <version>2.6.1</version>
</dependency>
----

[source,java]
----

@ApplicationScope
public class Main {
  public static void main(String... args) {
    SeContainerInitializer.newInstance().initilize();
  }
}

@ApplicationScoped
public class MyBean {
 @Outgoing("source")
    public PublisherBuilder<String> source() {
        return ReactiveStreams.of("hello", "with", "SmallRye", "reactive", "message");
    }

    @Incoming("source")
    @Outgoing("processed-a")
    public String toUpperCase(String payload) {
        return payload.toUpperCase();
    }

    @Incoming("processed-a")
    @Outgoing("processed-b")
    public PublisherBuilder<String> filter(PublisherBuilder<String> input) {
        return input.filter(item -> item.length() > 4);
    }

    @Incoming("processed-b")
    public void sink(String word) {
        System.out.println(">> " + word);
    }
}
----

When work with CDI using Apache Deltaspike or Jboss Weld bean.xml empty file is mandatory

[source,xml,subs=attributes+]
----
<beans
  xmlns="http://xmlns.jcp.org/xml/ns/javaee"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="
      http://xmlns.jcp.org/xml/ns/javaee
      http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
  bean-discovery-mode="annotated">
</beans>
----

[source,java]
----
package beans;

import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.eclipse.microprofile.reactive.messaging.Message;
import org.eclipse.microprofile.reactive.messaging.Outgoing;

import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class MessageProcessingBean {

    @Incoming("consumed-channel")
    @Outgoing("populated-channel")
    public Message<String> process(Message<String> in) {
        // Process the payload
        String payload = in.getPayload().toUpperCase();
        // Create a new message from `in` and just update the payload
        return in.withPayload(payload);
    }
}

----

.. Manipulating messages can be cumbersome.
When you are only interested in the payload, you can use the following syntax: The following code is equivalent to the snippet from above

[source,java]
----
package beans;

import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.eclipse.microprofile.reactive.messaging.Outgoing;

import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class PayloadProcessingBean {

    @Incoming("consumed-channel")
    @Outgoing("populated-channel")
    public String process(String in) {
        return in.toUpperCase();
    }
}
----

IMPORTANT: You should not call methods annotated with @Incoming and/or @Outgoing directly from your code.
They are invoked by the framework, having user code invoking them would not have the expected outcome

.. Methods annotated with @Incoming or @Outgoing don’t need to be in the same bean (class), and Remote interactions are also possible when using connectors.

== Return Ack
[source, java]
----
@Incoming("my-channel")
public Uni<Void> consumeMessageUni(Message<Price> message) {
    return Uni.createFrom().item(message)
        .onItem().invoke(m -> handle(m.getPayload()))
        .onItem().transformToUni(x -> Uni.createFrom().completionStage(message.ack()));
}
----

== Automatic Ack with Async behavior

[source, java]
----
@Incoming("my-channel")
public CompletionStage<Void> consumePayloadCS(Price payload) {
    CompletionStage<Void> cs = handleAsync(payload);
    return cs;
}

@Incoming("my-channel")
public Uni<Void> consumePayloadUni(Price payload) {
    return Uni.createFrom().item(payload)
        .onItem().invoke(this::handle)
        .onItem().ignore().andContinueWithNull();
}
----

== Connectors

=== Apache Kafka

. Kafka connector adds support for Kafka to Reactive Messaging

[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>smallrye-reactive-messaging-kafka</artifactId>
  <version>3.13.0</version>
</dependency>

----

....
# Inbound
mp.messaging.incoming.[channel-name].connector=smallrye-kafka

# Outbound
mp.messaging.outgoing.[channel-name].connector=smallrye-kafka
....