= Reactive Systems in Java

== Build Resilient, Event-Driven Architecture with https://quarkus.io/[Quarkus] and https://camel.apache.org/[Apache Camel]

== Links

- https://github.com/cescoffier/reactive-systems-in-java[Official Git Book Page]
- https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.13/index.html[SmallRye Reactive Messaging]
- https://camel.apache.org/components/3.14.x/kafka-component.html[Kakfa Component]

== PS Command RSS

[source,bash]
----
ps -e | grep thorntail
ps -o pid,rss,command -p {{id}} | awk '{$2=int($2/1024)"M";}{print;}'
java -Xmx48m -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -jar {{jar}}
./mvnw clean package -Dquarkus.kubernetes.deploy=true
----

== Use wrk tool to stress the app endpoint

[source,bash]
----
wrk -t 10 -c50 -d40s http://localhost:8080/hello
----

* Container density is a key characteristic of cloud deployments with Kubernetes

* The Reactive Manifesto

** _Responsive_ Able to handle requests in a timely fashion
** _Resilient_ Able to manage failure gracefully
** _Elastic_ Able to scale up and down according to the load and resources
** _Message Driven_ Using asynchronous message-based communication among the components forming the system, async messages ensures loose coupling, isolation and location transparency

[source,java]
----
class FooMulti {
  public Multi<Product> getRecommendations() {
    return Multi.createFrom().ticks().every(Duration.ofSeconds(1))
      .onOverflow().drop()
      .onItem().transformToUniAndConcatenate(x-> product.getRecommendedProduct());}
};
----

== Redis Cluster

[source,bash]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 --name redis_quarkus_test -p 6379:6379 redis:5.0.6
----

== Debezium Connector

[source,bash]
----
curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" http://localhost:8083/connectors/ -d @register.json
curl -H "Accept:application/json" localhost:8083/connectors/
curl -X GET -H "Accept:application/json" localhost:8083/connectors/customer-connector
----

== Check Kafka Topics

[source,bash]
----
docker exec -ti kafka bin/kafka-topics.sh --list --zookeeper zookeeper:2181
----

== Topics created

[source,html]
----
__consumer_offsets
my_connect_configs
my_connect_offsets
my_connect_statuses
quarkus-db-server.public.customer
quarkus-db-server.public.orders
----

== Camel Consumer Log from Update Operation PUT ##"name":"Marsha Willis 123"}##

[source,bash]
----
2022-01-29 11:31:34,557 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer]) Message received from Kafka : {"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":false,"field":"id"},{"type":"string","optional":false,"field":"name"}],"optional":true,"name":"quarkus_db_server.public.customer.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":false,"field":"id"},{"type":"string","optional":false,"field":"name"}],"optional":true,"name":"quarkus_db_server.public.customer.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"field":"transaction"}],"optional":false,"name":"quarkus_db_server.public.customer.Envelope"},"payload":{"before":null,"after":{"id":2,"name":"Marsha Willis 123"},"source":{"version":"1.5.4.Final","connector":"postgresql","name":"quarkus-db-server","ts_ms":1643466693971,"snapshot":"false","db":"quarkus_test","sequence":"[\"24203552\",\"24203552\"]","schema":"public","table":"customer","txId":542,"lsn":24203608,"xmin":null},"op":"u","ts_ms":1643466694089,"transaction":null}}

2022-01-29 11:31:34,558 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer])     on the topic quarkus-db-server.public.customer
2022-01-29 11:31:34,558 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer])     on the partition 0
2022-01-29 11:31:34,558 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer])     with the offset 17
2022-01-29 11:31:34,559 INFO  [route1] (Camel (camel-1) thread #1 - KafkaConsumer[quarkus-db-server.public.customer])     with the key {"schema":{"type":"struct","fields":[{"type":"int64","optional":false,"field":"id"}],"optional":false,"name":"quarkus_db_server.public.customer.Key"},"payload":{"id":2}}

----